### ISSUE TITLE
npm packages in the ".meteor/desktop-build" folder are outdated

### ISSUE THREAD

**Issue by a4xrbj1** [Meteor-Community-Packages/meteor-desktop#31]
The following npm packages in the `.meteor\desktop-build` folder are outdated:

 Patch Update Backwards-compatible bug fixes.
❯◯ lodash           4.17.15  ❯  4.17.21  https://lodash.com/
 ◯ request          2.88.0   ❯  2.88.2   https://github.com/request/request#readme
 ◯ request-promise  4.2.5    ❯  4.2.6    https://github.com/request/request-promise#readme

 Minor Update New backwards-compatible features.
 ◯ connect  3.6.6  ❯  3.7.0  https://github.com/senchalabs/connect#readme

 Major Update Potentially breaking API changes. Use caution.
 ◯ winston           2.3.0  ❯  3.10.0  https://github.com/winstonjs/winston#readme
 ◯ find-port         2.0.1  ❯  3.0.0   https://github.com/kessler/find-port#readme
 ◯ rimraf            2.6.2  ❯  5.0.5   https://github.com/isaacs/rimraf#readme
 ◯ queue             4.0.1  ❯  7.0.0   https://github.com/jessetane/queue#readme
 ◯ mime              2.0.3  ❯  3.0.0   https://github.com/broofa/mime#readme
 ◯ fs-extra          3.0.1  ❯  11.1.1  https://github.com/jprichardson/node-fs-extra
 ◯ fs-plus           2.9.3  ❯  3.1.1   http://atom.github.io/fs-plus
 ◯ electron-updater  5.0.5  ❯  6.1.4   https://github.com/electron-userland/electron-builder

 Non-Semver Versions less than 1.0.0, caution.
 ◯ shelljs  0.7.5   ❯  0.8.5    http://github.com/shelljs/shelljs
 ◯ reify    0.17.3  ❯  0.20.12  https://github.com/benjamn/reify#readme
 ◯ send     0.16.2  ❯  0.18.0   https://github.com/pillarjs/send#readme

1. Go to `.meteor\desktop-build` folder
2. Run npm-check -u (or similar) to see which packages are outdated

**Expected behavior**

No outdated npm packages

**Versions (please complete the following information):**
 - Meteor version: 2.12.0
 - Package version: 3.0.1

**Comment by StorytellerCZ** [comment]
We will have to split it further as some packages will need complete replacement like request. I will have a PR for few of them shortly.

**Comment by dd137** [comment]
@a4xrbj1 Would you mind updating the OP's list with the packages Jan has updated already (https://github.com/Meteor-Community-Packages/meteor-desktop/commit/893931f07986f730789f5d3efa3cd13fd14926f2)? 

It would be great if you tried updating the other packages too. Then we could include that in a v3.1.2? (IMHO 3.1.1 is ready for release and could be published from 3.1.1-rc.2)

**Comment by a4xrbj1** [comment]
All are working except `Winston`:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for winston@2.7.7.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
@jankapunkt - can you please use a version that exists and is compatible to the current NPM version that Meteor uses?

**Comment by dd137** [comment]
> All are working

Do you mean that you updated all dependencies as per the original post and everything runs fine? That's great. Are you planning to create a PR?

> except Winston:

I have already fixed the Winston issue (https://github.com/Meteor-Community-Packages/meteor-desktop/pull/13/commits/51f973b8bd5ad4714724330115fceac4cef189d6) (without major version bump), it should be fine since rc.1.

**Comment by StorytellerCZ** [comment]
Closing this as some were already updated and other are being updated.
